version: '3'

services:
  hub:
    build:
      context: ./hub
      dockerfile: Dockerfile
      args:
        JUPYTERHUB_VERSION: 5.2 # latest
    image: jupyterhub
    container_name: jupyterhub
    # command: jupyterhub -f /srv/jupyterhub/jupyterhub_config.py --debug
    environment:
      - LOCAL_VOLUME=${LOCAL_VOLUME}
    ports: 
      - 8000:8000
    volumes:
      - ./hub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
    depends_on: 
      db:
        condition: service_healthy
    networks:
      - jupyterhub-network
  db:
    image: mysql:9.1
    container_name: jupyterhub_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jupyterhub_db
    ports: 
      - 33060:33060
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - jupyterhub-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 2s
      retries: 2

networks:
  jupyterhub-network:
    name: jupyterhub-network

volumes:
    mysql-data:
